### ISSUE TITLE
Latest GA Releases fails to retrieve metrics queried for custom apps.

### ISSUE THREAD

**Issue by hanishi** [spring-cloud/spring-cloud-dataflow-metrics-collector#52]
I downloaded the jar from this url.
http://repo.spring.io/libs-release/org/springframework/cloud/metrics-collector-kafka-10/1.0.0.RELEASE/metrics-collector-kafka-10-1.0.0.RELEASE.jar and lanuched with the following paramter to be used with SCDF server.

`java -jar metrics-collector-kafka-10-1.0.0.RELEASE.jar --security.user.name=vagrant --security.user.password=vagrant --server.port=1234`

In SCDF, for the stream that is created with an OOTB app and deployed with the following parameter 
`app.*.spring.cloud.stream.bindings.applicationMetrics.destination=metrics`, identified as `foostream`,
 I can `curl`  the endpoint as follows and verify the response.
curl  http://localhost:1234/collector/metrics/streams?foostream

However, for my custom app, having defined a stream in SCDF and deployed with the same parameter, curling the endpoint in similar manner returned HTTP status code 500. I confirmed that the metrics values are to be found  both in the app's log and kafka topic.

When I built the `master` branch and run the produced jar using the same parameter as above and curled the same endpoint which has failed for the GA Release, I was able to get a successful response with JSON payload.

This issue is most likely related to [what is fixed after 1.0.0.RELEASE](https://github.com/spring-cloud/spring-cloud-dataflow-metrics-collector/commit/24425fb6a4570a97168b8f7ea488310328d1eee0) as pointed out by @ilayaperumalg in [gitter](https://gitter.im/spring-cloud/spring-cloud-dataflow) 

Since the bug has been already fixed and there is probably no need for any further action, this is just a reminder for developers who would confront the same problem 
I had.

It would be great if how this fix referred above affects the request made from SCDF server is explained here and the reason why  OOTB apps have worked.

**Comment by sabbyanandan** [comment]
Hi, @hanishi. We have recently released a 2.0 M1 version of this App, which also brings Spring Cloud Stream 2.0, Spring Boot 2.0 and Micrometer compatibility. We are also adding samples for Micrometer based InfluxDB and Prometheus based backends for a much comprehensive metrics coverage (see: spring-cloud/spring-cloud-dataflow-samples#56 and spring-cloud/spring-cloud-dataflow-samples#57). 

Since the 1.0 App is working for you at the moment, I'll close it. Please give it a go and let us know if you have any feedback on the latest release.
